[pytest]
# 告诉 pytest：每次运行时，自动清理旧数据，并把中间数据存到 reports/allure-results
addopts = --alluredir=./reports/allure-results --clean-alluredir
# 指定测试用例搜索路径，避免扫描到 src 或 data 里的文件
testpaths = tests
# 忽略生成的报告目录，避免重复扫描
norecursedirs = reports .venv